// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/server/ent/authaccount"
	"github.com/kilip/opus/server/ent/user"
)

// AuthAccountCreate is the builder for creating a AuthAccount entity.
type AuthAccountCreate struct {
	config
	mutation *AuthAccountMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AuthAccountCreate) SetUserID(v string) *AuthAccountCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AuthAccountCreate) SetAccountID(v string) *AuthAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *AuthAccountCreate) SetProviderID(v string) *AuthAccountCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *AuthAccountCreate) SetAccessToken(v string) *AuthAccountCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_c *AuthAccountCreate) SetNillableAccessToken(v *string) *AuthAccountCreate {
	if v != nil {
		_c.SetAccessToken(*v)
	}
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *AuthAccountCreate) SetRefreshToken(v string) *AuthAccountCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_c *AuthAccountCreate) SetNillableRefreshToken(v *string) *AuthAccountCreate {
	if v != nil {
		_c.SetRefreshToken(*v)
	}
	return _c
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_c *AuthAccountCreate) SetAccessTokenExpiresAt(v time.Time) *AuthAccountCreate {
	_c.mutation.SetAccessTokenExpiresAt(v)
	return _c
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_c *AuthAccountCreate) SetNillableAccessTokenExpiresAt(v *time.Time) *AuthAccountCreate {
	if v != nil {
		_c.SetAccessTokenExpiresAt(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *AuthAccountCreate) SetScope(v string) *AuthAccountCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *AuthAccountCreate) SetNillableScope(v *string) *AuthAccountCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthAccountCreate) SetCreatedAt(v time.Time) *AuthAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthAccountCreate) SetNillableCreatedAt(v *time.Time) *AuthAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthAccountCreate) SetUpdatedAt(v time.Time) *AuthAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthAccountCreate) SetNillableUpdatedAt(v *time.Time) *AuthAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthAccountCreate) SetID(v string) *AuthAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AuthAccountCreate) SetUser(v *User) *AuthAccountCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AuthAccountMutation object of the builder.
func (_c *AuthAccountCreate) Mutation() *AuthAccountMutation {
	return _c.mutation
}

// Save creates the AuthAccount in the database.
func (_c *AuthAccountCreate) Save(ctx context.Context) (*AuthAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthAccountCreate) SaveX(ctx context.Context) *AuthAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthAccountCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuthAccount.user_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AuthAccount.account_id"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "AuthAccount.provider_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthAccount.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AuthAccount.user"`)}
	}
	return nil
}

func (_c *AuthAccountCreate) sqlSave(ctx context.Context) (*AuthAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuthAccount.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthAccountCreate) createSpec() (*AuthAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authaccount.Table, sqlgraph.NewFieldSpec(authaccount.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(authaccount.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(authaccount.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(authaccount.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(authaccount.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(authaccount.FieldAccessTokenExpiresAt, field.TypeTime, value)
		_node.AccessTokenExpiresAt = &value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(authaccount.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authaccount.UserTable,
			Columns: []string{authaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuthAccountCreateBulk is the builder for creating many AuthAccount entities in bulk.
type AuthAccountCreateBulk struct {
	config
	err      error
	builders []*AuthAccountCreate
}

// Save creates the AuthAccount entities in the database.
func (_c *AuthAccountCreateBulk) Save(ctx context.Context) ([]*AuthAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthAccountCreateBulk) SaveX(ctx context.Context) []*AuthAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
