// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/server/ent/authoauthstate"
)

// AuthOauthStateCreate is the builder for creating a AuthOauthState entity.
type AuthOauthStateCreate struct {
	config
	mutation *AuthOauthStateMutation
	hooks    []Hook
}

// SetState sets the "state" field.
func (_c *AuthOauthStateCreate) SetState(v string) *AuthOauthStateCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *AuthOauthStateCreate) SetProviderID(v string) *AuthOauthStateCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthOauthStateCreate) SetExpiresAt(v time.Time) *AuthOauthStateCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthOauthStateCreate) SetCreatedAt(v time.Time) *AuthOauthStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthOauthStateCreate) SetNillableCreatedAt(v *time.Time) *AuthOauthStateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthOauthStateCreate) SetID(v string) *AuthOauthStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthOauthStateMutation object of the builder.
func (_c *AuthOauthStateCreate) Mutation() *AuthOauthStateMutation {
	return _c.mutation
}

// Save creates the AuthOauthState in the database.
func (_c *AuthOauthStateCreate) Save(ctx context.Context) (*AuthOauthState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthOauthStateCreate) SaveX(ctx context.Context) *AuthOauthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthOauthStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthOauthStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthOauthStateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authoauthstate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthOauthStateCreate) check() error {
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "AuthOauthState.state"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "AuthOauthState.provider_id"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthOauthState.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthOauthState.created_at"`)}
	}
	return nil
}

func (_c *AuthOauthStateCreate) sqlSave(ctx context.Context) (*AuthOauthState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuthOauthState.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthOauthStateCreate) createSpec() (*AuthOauthState, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthOauthState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authoauthstate.Table, sqlgraph.NewFieldSpec(authoauthstate.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(authoauthstate.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(authoauthstate.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authoauthstate.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authoauthstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AuthOauthStateCreateBulk is the builder for creating many AuthOauthState entities in bulk.
type AuthOauthStateCreateBulk struct {
	config
	err      error
	builders []*AuthOauthStateCreate
}

// Save creates the AuthOauthState entities in the database.
func (_c *AuthOauthStateCreateBulk) Save(ctx context.Context) ([]*AuthOauthState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthOauthState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthOauthStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthOauthStateCreateBulk) SaveX(ctx context.Context) []*AuthOauthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthOauthStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthOauthStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
