// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/server/ent/authoauthstate"
	"github.com/kilip/opus/server/ent/predicate"
)

// AuthOauthStateUpdate is the builder for updating AuthOauthState entities.
type AuthOauthStateUpdate struct {
	config
	hooks    []Hook
	mutation *AuthOauthStateMutation
}

// Where appends a list predicates to the AuthOauthStateUpdate builder.
func (_u *AuthOauthStateUpdate) Where(ps ...predicate.AuthOauthState) *AuthOauthStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *AuthOauthStateUpdate) SetState(v string) *AuthOauthStateUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AuthOauthStateUpdate) SetNillableState(v *string) *AuthOauthStateUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *AuthOauthStateUpdate) SetProviderID(v string) *AuthOauthStateUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AuthOauthStateUpdate) SetNillableProviderID(v *string) *AuthOauthStateUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthOauthStateUpdate) SetExpiresAt(v time.Time) *AuthOauthStateUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthOauthStateUpdate) SetNillableExpiresAt(v *time.Time) *AuthOauthStateUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the AuthOauthStateMutation object of the builder.
func (_u *AuthOauthStateUpdate) Mutation() *AuthOauthStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthOauthStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthOauthStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthOauthStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthOauthStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthOauthStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authoauthstate.Table, authoauthstate.Columns, sqlgraph.NewFieldSpec(authoauthstate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(authoauthstate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(authoauthstate.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authoauthstate.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authoauthstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthOauthStateUpdateOne is the builder for updating a single AuthOauthState entity.
type AuthOauthStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthOauthStateMutation
}

// SetState sets the "state" field.
func (_u *AuthOauthStateUpdateOne) SetState(v string) *AuthOauthStateUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AuthOauthStateUpdateOne) SetNillableState(v *string) *AuthOauthStateUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *AuthOauthStateUpdateOne) SetProviderID(v string) *AuthOauthStateUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AuthOauthStateUpdateOne) SetNillableProviderID(v *string) *AuthOauthStateUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthOauthStateUpdateOne) SetExpiresAt(v time.Time) *AuthOauthStateUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthOauthStateUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthOauthStateUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the AuthOauthStateMutation object of the builder.
func (_u *AuthOauthStateUpdateOne) Mutation() *AuthOauthStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthOauthStateUpdate builder.
func (_u *AuthOauthStateUpdateOne) Where(ps ...predicate.AuthOauthState) *AuthOauthStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthOauthStateUpdateOne) Select(field string, fields ...string) *AuthOauthStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthOauthState entity.
func (_u *AuthOauthStateUpdateOne) Save(ctx context.Context) (*AuthOauthState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthOauthStateUpdateOne) SaveX(ctx context.Context) *AuthOauthState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthOauthStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthOauthStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthOauthStateUpdateOne) sqlSave(ctx context.Context) (_node *AuthOauthState, err error) {
	_spec := sqlgraph.NewUpdateSpec(authoauthstate.Table, authoauthstate.Columns, sqlgraph.NewFieldSpec(authoauthstate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthOauthState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authoauthstate.FieldID)
		for _, f := range fields {
			if !authoauthstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authoauthstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(authoauthstate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(authoauthstate.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authoauthstate.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &AuthOauthState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authoauthstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
