# opus/Taskfile.yml
version: "3"

dotenv: ['.env']

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

  dash:
    taskfile: ./dash/Taskfile.yml
    dir: ./dash

  installer:
    taskfile: ./installer/Taskfile.yml
    dir: ./installer

tasks:
  setup:
    desc: Install all dependencies
    deps: [setup:env, api:setup, dash:setup, installer:setup]

  setup:env:
    desc: Create .env from .env.example if it doesn't exist
    cmds:
      - cp .env.example .env
    status:
      - test -f .env

  dev:
    desc: Start api/ and dash/ in development mode concurrently
    deps: [setup:env, api:dev, dash:dev]

  build:
    desc: Build all components
    deps: [api:build, dash:build, installer:build]

  test:all:
    desc: Run all tests
    deps: [lint, api:test:all, dash:test]

  lint:
    desc: Lint all components
    deps: [api:lint, dash:lint, installer:lint]

  migrate:
    desc: Run database migrations
    cmds:
      - task: api:migrate
