// Code generated by ent, DO NOT EDIT.

package wachat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the wachat type in the database.
	Label = "wa_chat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJid holds the string denoting the jid field in the database.
	FieldJid = "jid"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUnreadCount holds the string denoting the unread_count field in the database.
	FieldUnreadCount = "unread_count"
	// EdgeWaSession holds the string denoting the wa_session edge name in mutations.
	EdgeWaSession = "wa_session"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the wachat in the database.
	Table = "wa_chats"
	// WaSessionTable is the table that holds the wa_session relation/edge.
	WaSessionTable = "wa_chats"
	// WaSessionInverseTable is the table name for the WaSession entity.
	// It exists in this package in order to avoid circular dependency with the "wasession" package.
	WaSessionInverseTable = "wa_sessions"
	// WaSessionColumn is the table column denoting the wa_session relation/edge.
	WaSessionColumn = "wa_session_chats"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "wa_messages"
	// MessagesInverseTable is the table name for the WaMessage entity.
	// It exists in this package in order to avoid circular dependency with the "wamessage" package.
	MessagesInverseTable = "wa_messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "wa_chat_messages"
)

// Columns holds all SQL columns for wachat fields.
var Columns = []string{
	FieldID,
	FieldJid,
	FieldName,
	FieldUnreadCount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "wa_chats"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"wa_session_chats",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUnreadCount holds the default value on creation for the "unread_count" field.
	DefaultUnreadCount int
)

// OrderOption defines the ordering options for the WaChat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJid orders the results by the jid field.
func ByJid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJid, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByUnreadCount orders the results by the unread_count field.
func ByUnreadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnreadCount, opts...).ToFunc()
}

// ByWaSessionField orders the results by wa_session field.
func ByWaSessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWaSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newWaSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WaSessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WaSessionTable, WaSessionColumn),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
