// Code generated by ent, DO NOT EDIT.

package wacontact

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the wacontact type in the database.
	Label = "wa_contact"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJid holds the string denoting the jid field in the database.
	FieldJid = "jid"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPushname holds the string denoting the pushname field in the database.
	FieldPushname = "pushname"
	// EdgeWaSession holds the string denoting the wa_session edge name in mutations.
	EdgeWaSession = "wa_session"
	// Table holds the table name of the wacontact in the database.
	Table = "wa_contacts"
	// WaSessionTable is the table that holds the wa_session relation/edge.
	WaSessionTable = "wa_contacts"
	// WaSessionInverseTable is the table name for the WaSession entity.
	// It exists in this package in order to avoid circular dependency with the "wasession" package.
	WaSessionInverseTable = "wa_sessions"
	// WaSessionColumn is the table column denoting the wa_session relation/edge.
	WaSessionColumn = "wa_session_contacts"
)

// Columns holds all SQL columns for wacontact fields.
var Columns = []string{
	FieldID,
	FieldJid,
	FieldName,
	FieldPushname,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "wa_contacts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"wa_session_contacts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the WaContact queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJid orders the results by the jid field.
func ByJid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJid, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPushname orders the results by the pushname field.
func ByPushname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPushname, opts...).ToFunc()
}

// ByWaSessionField orders the results by wa_session field.
func ByWaSessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWaSessionStep(), sql.OrderByField(field, opts...))
	}
}
func newWaSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WaSessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WaSessionTable, WaSessionColumn),
	)
}
