// Code generated by ent, DO NOT EDIT.

package wacontact

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kilip/opus/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WaContact {
	return predicate.WaContact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WaContact {
	return predicate.WaContact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WaContact {
	return predicate.WaContact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WaContact {
	return predicate.WaContact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WaContact {
	return predicate.WaContact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WaContact {
	return predicate.WaContact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WaContact {
	return predicate.WaContact(sql.FieldLTE(FieldID, id))
}

// Jid applies equality check predicate on the "jid" field. It's identical to JidEQ.
func Jid(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldJid, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldName, v))
}

// Pushname applies equality check predicate on the "pushname" field. It's identical to PushnameEQ.
func Pushname(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldPushname, v))
}

// JidEQ applies the EQ predicate on the "jid" field.
func JidEQ(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldJid, v))
}

// JidNEQ applies the NEQ predicate on the "jid" field.
func JidNEQ(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldNEQ(FieldJid, v))
}

// JidIn applies the In predicate on the "jid" field.
func JidIn(vs ...string) predicate.WaContact {
	return predicate.WaContact(sql.FieldIn(FieldJid, vs...))
}

// JidNotIn applies the NotIn predicate on the "jid" field.
func JidNotIn(vs ...string) predicate.WaContact {
	return predicate.WaContact(sql.FieldNotIn(FieldJid, vs...))
}

// JidGT applies the GT predicate on the "jid" field.
func JidGT(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldGT(FieldJid, v))
}

// JidGTE applies the GTE predicate on the "jid" field.
func JidGTE(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldGTE(FieldJid, v))
}

// JidLT applies the LT predicate on the "jid" field.
func JidLT(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldLT(FieldJid, v))
}

// JidLTE applies the LTE predicate on the "jid" field.
func JidLTE(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldLTE(FieldJid, v))
}

// JidContains applies the Contains predicate on the "jid" field.
func JidContains(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldContains(FieldJid, v))
}

// JidHasPrefix applies the HasPrefix predicate on the "jid" field.
func JidHasPrefix(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldHasPrefix(FieldJid, v))
}

// JidHasSuffix applies the HasSuffix predicate on the "jid" field.
func JidHasSuffix(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldHasSuffix(FieldJid, v))
}

// JidEqualFold applies the EqualFold predicate on the "jid" field.
func JidEqualFold(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEqualFold(FieldJid, v))
}

// JidContainsFold applies the ContainsFold predicate on the "jid" field.
func JidContainsFold(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldContainsFold(FieldJid, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.WaContact {
	return predicate.WaContact(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.WaContact {
	return predicate.WaContact(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldContainsFold(FieldName, v))
}

// PushnameEQ applies the EQ predicate on the "pushname" field.
func PushnameEQ(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEQ(FieldPushname, v))
}

// PushnameNEQ applies the NEQ predicate on the "pushname" field.
func PushnameNEQ(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldNEQ(FieldPushname, v))
}

// PushnameIn applies the In predicate on the "pushname" field.
func PushnameIn(vs ...string) predicate.WaContact {
	return predicate.WaContact(sql.FieldIn(FieldPushname, vs...))
}

// PushnameNotIn applies the NotIn predicate on the "pushname" field.
func PushnameNotIn(vs ...string) predicate.WaContact {
	return predicate.WaContact(sql.FieldNotIn(FieldPushname, vs...))
}

// PushnameGT applies the GT predicate on the "pushname" field.
func PushnameGT(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldGT(FieldPushname, v))
}

// PushnameGTE applies the GTE predicate on the "pushname" field.
func PushnameGTE(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldGTE(FieldPushname, v))
}

// PushnameLT applies the LT predicate on the "pushname" field.
func PushnameLT(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldLT(FieldPushname, v))
}

// PushnameLTE applies the LTE predicate on the "pushname" field.
func PushnameLTE(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldLTE(FieldPushname, v))
}

// PushnameContains applies the Contains predicate on the "pushname" field.
func PushnameContains(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldContains(FieldPushname, v))
}

// PushnameHasPrefix applies the HasPrefix predicate on the "pushname" field.
func PushnameHasPrefix(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldHasPrefix(FieldPushname, v))
}

// PushnameHasSuffix applies the HasSuffix predicate on the "pushname" field.
func PushnameHasSuffix(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldHasSuffix(FieldPushname, v))
}

// PushnameIsNil applies the IsNil predicate on the "pushname" field.
func PushnameIsNil() predicate.WaContact {
	return predicate.WaContact(sql.FieldIsNull(FieldPushname))
}

// PushnameNotNil applies the NotNil predicate on the "pushname" field.
func PushnameNotNil() predicate.WaContact {
	return predicate.WaContact(sql.FieldNotNull(FieldPushname))
}

// PushnameEqualFold applies the EqualFold predicate on the "pushname" field.
func PushnameEqualFold(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldEqualFold(FieldPushname, v))
}

// PushnameContainsFold applies the ContainsFold predicate on the "pushname" field.
func PushnameContainsFold(v string) predicate.WaContact {
	return predicate.WaContact(sql.FieldContainsFold(FieldPushname, v))
}

// HasWaSession applies the HasEdge predicate on the "wa_session" edge.
func HasWaSession() predicate.WaContact {
	return predicate.WaContact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WaSessionTable, WaSessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWaSessionWith applies the HasEdge predicate on the "wa_session" edge with a given conditions (other predicates).
func HasWaSessionWith(preds ...predicate.WaSession) predicate.WaContact {
	return predicate.WaContact(func(s *sql.Selector) {
		step := newWaSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WaContact) predicate.WaContact {
	return predicate.WaContact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WaContact) predicate.WaContact {
	return predicate.WaContact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WaContact) predicate.WaContact {
	return predicate.WaContact(sql.NotPredicates(p))
}
