// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/cronschedule"
)

// CronScheduleCreate is the builder for creating a CronSchedule entity.
type CronScheduleCreate struct {
	config
	mutation *CronScheduleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CronScheduleCreate) SetName(v string) *CronScheduleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCronExpression sets the "cron_expression" field.
func (_c *CronScheduleCreate) SetCronExpression(v string) *CronScheduleCreate {
	_c.mutation.SetCronExpression(v)
	return _c
}

// SetJobType sets the "job_type" field.
func (_c *CronScheduleCreate) SetJobType(v string) *CronScheduleCreate {
	_c.mutation.SetJobType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *CronScheduleCreate) SetPayload(v []byte) *CronScheduleCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *CronScheduleCreate) SetIsActive(v bool) *CronScheduleCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *CronScheduleCreate) SetNillableIsActive(v *bool) *CronScheduleCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *CronScheduleCreate) SetLastRunAt(v time.Time) *CronScheduleCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_c *CronScheduleCreate) SetNillableLastRunAt(v *time.Time) *CronScheduleCreate {
	if v != nil {
		_c.SetLastRunAt(*v)
	}
	return _c
}

// SetNextRunAt sets the "next_run_at" field.
func (_c *CronScheduleCreate) SetNextRunAt(v time.Time) *CronScheduleCreate {
	_c.mutation.SetNextRunAt(v)
	return _c
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_c *CronScheduleCreate) SetNillableNextRunAt(v *time.Time) *CronScheduleCreate {
	if v != nil {
		_c.SetNextRunAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CronScheduleCreate) SetCreatedAt(v time.Time) *CronScheduleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CronScheduleCreate) SetNillableCreatedAt(v *time.Time) *CronScheduleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CronScheduleCreate) SetUpdatedAt(v time.Time) *CronScheduleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CronScheduleCreate) SetNillableUpdatedAt(v *time.Time) *CronScheduleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CronScheduleCreate) SetID(v string) *CronScheduleCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CronScheduleMutation object of the builder.
func (_c *CronScheduleCreate) Mutation() *CronScheduleMutation {
	return _c.mutation
}

// Save creates the CronSchedule in the database.
func (_c *CronScheduleCreate) Save(ctx context.Context) (*CronSchedule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CronScheduleCreate) SaveX(ctx context.Context) *CronSchedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CronScheduleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CronScheduleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CronScheduleCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := cronschedule.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cronschedule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cronschedule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CronScheduleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CronSchedule.name"`)}
	}
	if _, ok := _c.mutation.CronExpression(); !ok {
		return &ValidationError{Name: "cron_expression", err: errors.New(`ent: missing required field "CronSchedule.cron_expression"`)}
	}
	if _, ok := _c.mutation.JobType(); !ok {
		return &ValidationError{Name: "job_type", err: errors.New(`ent: missing required field "CronSchedule.job_type"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "CronSchedule.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CronSchedule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CronSchedule.updated_at"`)}
	}
	return nil
}

func (_c *CronScheduleCreate) sqlSave(ctx context.Context) (*CronSchedule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CronSchedule.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CronScheduleCreate) createSpec() (*CronSchedule, *sqlgraph.CreateSpec) {
	var (
		_node = &CronSchedule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cronschedule.Table, sqlgraph.NewFieldSpec(cronschedule.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(cronschedule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CronExpression(); ok {
		_spec.SetField(cronschedule.FieldCronExpression, field.TypeString, value)
		_node.CronExpression = value
	}
	if value, ok := _c.mutation.JobType(); ok {
		_spec.SetField(cronschedule.FieldJobType, field.TypeString, value)
		_node.JobType = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(cronschedule.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(cronschedule.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(cronschedule.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = value
	}
	if value, ok := _c.mutation.NextRunAt(); ok {
		_spec.SetField(cronschedule.FieldNextRunAt, field.TypeTime, value)
		_node.NextRunAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cronschedule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cronschedule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CronScheduleCreateBulk is the builder for creating many CronSchedule entities in bulk.
type CronScheduleCreateBulk struct {
	config
	err      error
	builders []*CronScheduleCreate
}

// Save creates the CronSchedule entities in the database.
func (_c *CronScheduleCreateBulk) Save(ctx context.Context) ([]*CronSchedule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CronSchedule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CronScheduleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CronScheduleCreateBulk) SaveX(ctx context.Context) []*CronSchedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CronScheduleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CronScheduleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
