// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/deadletter"
)

// DeadLetterCreate is the builder for creating a DeadLetter entity.
type DeadLetterCreate struct {
	config
	mutation *DeadLetterMutation
	hooks    []Hook
}

// SetJobID sets the "job_id" field.
func (_c *DeadLetterCreate) SetJobID(v string) *DeadLetterCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *DeadLetterCreate) SetType(v string) *DeadLetterCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *DeadLetterCreate) SetPayload(v []byte) *DeadLetterCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *DeadLetterCreate) SetLastError(v string) *DeadLetterCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *DeadLetterCreate) SetNillableLastError(v *string) *DeadLetterCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetRetries sets the "retries" field.
func (_c *DeadLetterCreate) SetRetries(v int) *DeadLetterCreate {
	_c.mutation.SetRetries(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeadLetterCreate) SetCreatedAt(v time.Time) *DeadLetterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeadLetterCreate) SetNillableCreatedAt(v *time.Time) *DeadLetterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeadLetterCreate) SetID(v string) *DeadLetterCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DeadLetterMutation object of the builder.
func (_c *DeadLetterCreate) Mutation() *DeadLetterMutation {
	return _c.mutation
}

// Save creates the DeadLetter in the database.
func (_c *DeadLetterCreate) Save(ctx context.Context) (*DeadLetter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeadLetterCreate) SaveX(ctx context.Context) *DeadLetter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeadLetterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeadLetterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeadLetterCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deadletter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeadLetterCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "DeadLetter.job_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "DeadLetter.type"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "DeadLetter.payload"`)}
	}
	if _, ok := _c.mutation.Retries(); !ok {
		return &ValidationError{Name: "retries", err: errors.New(`ent: missing required field "DeadLetter.retries"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeadLetter.created_at"`)}
	}
	return nil
}

func (_c *DeadLetterCreate) sqlSave(ctx context.Context) (*DeadLetter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DeadLetter.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeadLetterCreate) createSpec() (*DeadLetter, *sqlgraph.CreateSpec) {
	var (
		_node = &DeadLetter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deadletter.Table, sqlgraph.NewFieldSpec(deadletter.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(deadletter.FieldJobID, field.TypeString, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(deadletter.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(deadletter.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(deadletter.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.Retries(); ok {
		_spec.SetField(deadletter.FieldRetries, field.TypeInt, value)
		_node.Retries = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deadletter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DeadLetterCreateBulk is the builder for creating many DeadLetter entities in bulk.
type DeadLetterCreateBulk struct {
	config
	err      error
	builders []*DeadLetterCreate
}

// Save creates the DeadLetter entities in the database.
func (_c *DeadLetterCreateBulk) Save(ctx context.Context) ([]*DeadLetter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeadLetter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeadLetterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeadLetterCreateBulk) SaveX(ctx context.Context) []*DeadLetter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeadLetterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeadLetterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
