// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/job"
	"github.com/kilip/opus/api/ent/predicate"
	"github.com/kilip/opus/api/ent/user"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *JobUpdate) SetType(v string) *JobUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *JobUpdate) SetNillableType(v *string) *JobUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdate) SetPayload(v []byte) *JobUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *JobUpdate) SetPriority(v int) *JobUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *JobUpdate) SetNillablePriority(v *int) *JobUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *JobUpdate) AddPriority(v int) *JobUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdate) SetStatus(v string) *JobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStatus(v *string) *JobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetries sets the "retries" field.
func (_u *JobUpdate) SetRetries(v int) *JobUpdate {
	_u.mutation.ResetRetries()
	_u.mutation.SetRetries(v)
	return _u
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (_u *JobUpdate) SetNillableRetries(v *int) *JobUpdate {
	if v != nil {
		_u.SetRetries(*v)
	}
	return _u
}

// AddRetries adds value to the "retries" field.
func (_u *JobUpdate) AddRetries(v int) *JobUpdate {
	_u.mutation.AddRetries(v)
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *JobUpdate) SetMaxRetries(v int) *JobUpdate {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *JobUpdate) SetNillableMaxRetries(v *int) *JobUpdate {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *JobUpdate) AddMaxRetries(v int) *JobUpdate {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *JobUpdate) SetScheduledAt(v time.Time) *JobUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableScheduledAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobUpdate) SetUpdatedAt(v time.Time) *JobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetError sets the "error" field.
func (_u *JobUpdate) SetError(v string) *JobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *JobUpdate) SetNillableError(v *string) *JobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *JobUpdate) ClearError() *JobUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *JobUpdate) SetUserID(v string) *JobUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *JobUpdate) SetNillableUserID(v *string) *JobUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *JobUpdate) SetUser(v *User) *JobUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *JobUpdate) ClearUser() *JobUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Job.user"`)
	}
	return nil
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(job.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(job.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(job.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retries(); ok {
		_spec.SetField(job.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetries(); ok {
		_spec.AddField(job.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(job.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(job.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(job.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(job.FieldError, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetType sets the "type" field.
func (_u *JobUpdateOne) SetType(v string) *JobUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableType(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdateOne) SetPayload(v []byte) *JobUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *JobUpdateOne) SetPriority(v int) *JobUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillablePriority(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *JobUpdateOne) AddPriority(v int) *JobUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdateOne) SetStatus(v string) *JobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStatus(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetries sets the "retries" field.
func (_u *JobUpdateOne) SetRetries(v int) *JobUpdateOne {
	_u.mutation.ResetRetries()
	_u.mutation.SetRetries(v)
	return _u
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableRetries(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetRetries(*v)
	}
	return _u
}

// AddRetries adds value to the "retries" field.
func (_u *JobUpdateOne) AddRetries(v int) *JobUpdateOne {
	_u.mutation.AddRetries(v)
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *JobUpdateOne) SetMaxRetries(v int) *JobUpdateOne {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableMaxRetries(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *JobUpdateOne) AddMaxRetries(v int) *JobUpdateOne {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *JobUpdateOne) SetScheduledAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableScheduledAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobUpdateOne) SetUpdatedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetError sets the "error" field.
func (_u *JobUpdateOne) SetError(v string) *JobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableError(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *JobUpdateOne) ClearError() *JobUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *JobUpdateOne) SetUserID(v string) *JobUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableUserID(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *JobUpdateOne) SetUser(v *User) *JobUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *JobUpdateOne) ClearUser() *JobUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Job.user"`)
	}
	return nil
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(job.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(job.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(job.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retries(); ok {
		_spec.SetField(job.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetries(); ok {
		_spec.AddField(job.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(job.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(job.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(job.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(job.FieldError, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
