// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/predicate"
	"github.com/kilip/opus/api/ent/wachat"
	"github.com/kilip/opus/api/ent/wamessage"
	"github.com/kilip/opus/api/ent/wasession"
)

// WaChatUpdate is the builder for updating WaChat entities.
type WaChatUpdate struct {
	config
	hooks    []Hook
	mutation *WaChatMutation
}

// Where appends a list predicates to the WaChatUpdate builder.
func (_u *WaChatUpdate) Where(ps ...predicate.WaChat) *WaChatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJid sets the "jid" field.
func (_u *WaChatUpdate) SetJid(v string) *WaChatUpdate {
	_u.mutation.SetJid(v)
	return _u
}

// SetNillableJid sets the "jid" field if the given value is not nil.
func (_u *WaChatUpdate) SetNillableJid(v *string) *WaChatUpdate {
	if v != nil {
		_u.SetJid(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WaChatUpdate) SetName(v string) *WaChatUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WaChatUpdate) SetNillableName(v *string) *WaChatUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WaChatUpdate) ClearName() *WaChatUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetUnreadCount sets the "unread_count" field.
func (_u *WaChatUpdate) SetUnreadCount(v int) *WaChatUpdate {
	_u.mutation.ResetUnreadCount()
	_u.mutation.SetUnreadCount(v)
	return _u
}

// SetNillableUnreadCount sets the "unread_count" field if the given value is not nil.
func (_u *WaChatUpdate) SetNillableUnreadCount(v *int) *WaChatUpdate {
	if v != nil {
		_u.SetUnreadCount(*v)
	}
	return _u
}

// AddUnreadCount adds value to the "unread_count" field.
func (_u *WaChatUpdate) AddUnreadCount(v int) *WaChatUpdate {
	_u.mutation.AddUnreadCount(v)
	return _u
}

// SetWaSessionID sets the "wa_session" edge to the WaSession entity by ID.
func (_u *WaChatUpdate) SetWaSessionID(id string) *WaChatUpdate {
	_u.mutation.SetWaSessionID(id)
	return _u
}

// SetWaSession sets the "wa_session" edge to the WaSession entity.
func (_u *WaChatUpdate) SetWaSession(v *WaSession) *WaChatUpdate {
	return _u.SetWaSessionID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the WaMessage entity by IDs.
func (_u *WaChatUpdate) AddMessageIDs(ids ...int) *WaChatUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the WaMessage entity.
func (_u *WaChatUpdate) AddMessages(v ...*WaMessage) *WaChatUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the WaChatMutation object of the builder.
func (_u *WaChatUpdate) Mutation() *WaChatMutation {
	return _u.mutation
}

// ClearWaSession clears the "wa_session" edge to the WaSession entity.
func (_u *WaChatUpdate) ClearWaSession() *WaChatUpdate {
	_u.mutation.ClearWaSession()
	return _u
}

// ClearMessages clears all "messages" edges to the WaMessage entity.
func (_u *WaChatUpdate) ClearMessages() *WaChatUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to WaMessage entities by IDs.
func (_u *WaChatUpdate) RemoveMessageIDs(ids ...int) *WaChatUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to WaMessage entities.
func (_u *WaChatUpdate) RemoveMessages(v ...*WaMessage) *WaChatUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WaChatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WaChatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WaChatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WaChatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WaChatUpdate) check() error {
	if _u.mutation.WaSessionCleared() && len(_u.mutation.WaSessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WaChat.wa_session"`)
	}
	return nil
}

func (_u *WaChatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wachat.Table, wachat.Columns, sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Jid(); ok {
		_spec.SetField(wachat.FieldJid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(wachat.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(wachat.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.UnreadCount(); ok {
		_spec.SetField(wachat.FieldUnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnreadCount(); ok {
		_spec.AddField(wachat.FieldUnreadCount, field.TypeInt, value)
	}
	if _u.mutation.WaSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wachat.WaSessionTable,
			Columns: []string{wachat.WaSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WaSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wachat.WaSessionTable,
			Columns: []string{wachat.WaSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wachat.MessagesTable,
			Columns: []string{wachat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wachat.MessagesTable,
			Columns: []string{wachat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wachat.MessagesTable,
			Columns: []string{wachat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wachat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WaChatUpdateOne is the builder for updating a single WaChat entity.
type WaChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WaChatMutation
}

// SetJid sets the "jid" field.
func (_u *WaChatUpdateOne) SetJid(v string) *WaChatUpdateOne {
	_u.mutation.SetJid(v)
	return _u
}

// SetNillableJid sets the "jid" field if the given value is not nil.
func (_u *WaChatUpdateOne) SetNillableJid(v *string) *WaChatUpdateOne {
	if v != nil {
		_u.SetJid(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WaChatUpdateOne) SetName(v string) *WaChatUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WaChatUpdateOne) SetNillableName(v *string) *WaChatUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WaChatUpdateOne) ClearName() *WaChatUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetUnreadCount sets the "unread_count" field.
func (_u *WaChatUpdateOne) SetUnreadCount(v int) *WaChatUpdateOne {
	_u.mutation.ResetUnreadCount()
	_u.mutation.SetUnreadCount(v)
	return _u
}

// SetNillableUnreadCount sets the "unread_count" field if the given value is not nil.
func (_u *WaChatUpdateOne) SetNillableUnreadCount(v *int) *WaChatUpdateOne {
	if v != nil {
		_u.SetUnreadCount(*v)
	}
	return _u
}

// AddUnreadCount adds value to the "unread_count" field.
func (_u *WaChatUpdateOne) AddUnreadCount(v int) *WaChatUpdateOne {
	_u.mutation.AddUnreadCount(v)
	return _u
}

// SetWaSessionID sets the "wa_session" edge to the WaSession entity by ID.
func (_u *WaChatUpdateOne) SetWaSessionID(id string) *WaChatUpdateOne {
	_u.mutation.SetWaSessionID(id)
	return _u
}

// SetWaSession sets the "wa_session" edge to the WaSession entity.
func (_u *WaChatUpdateOne) SetWaSession(v *WaSession) *WaChatUpdateOne {
	return _u.SetWaSessionID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the WaMessage entity by IDs.
func (_u *WaChatUpdateOne) AddMessageIDs(ids ...int) *WaChatUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the WaMessage entity.
func (_u *WaChatUpdateOne) AddMessages(v ...*WaMessage) *WaChatUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the WaChatMutation object of the builder.
func (_u *WaChatUpdateOne) Mutation() *WaChatMutation {
	return _u.mutation
}

// ClearWaSession clears the "wa_session" edge to the WaSession entity.
func (_u *WaChatUpdateOne) ClearWaSession() *WaChatUpdateOne {
	_u.mutation.ClearWaSession()
	return _u
}

// ClearMessages clears all "messages" edges to the WaMessage entity.
func (_u *WaChatUpdateOne) ClearMessages() *WaChatUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to WaMessage entities by IDs.
func (_u *WaChatUpdateOne) RemoveMessageIDs(ids ...int) *WaChatUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to WaMessage entities.
func (_u *WaChatUpdateOne) RemoveMessages(v ...*WaMessage) *WaChatUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the WaChatUpdate builder.
func (_u *WaChatUpdateOne) Where(ps ...predicate.WaChat) *WaChatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WaChatUpdateOne) Select(field string, fields ...string) *WaChatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WaChat entity.
func (_u *WaChatUpdateOne) Save(ctx context.Context) (*WaChat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WaChatUpdateOne) SaveX(ctx context.Context) *WaChat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WaChatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WaChatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WaChatUpdateOne) check() error {
	if _u.mutation.WaSessionCleared() && len(_u.mutation.WaSessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WaChat.wa_session"`)
	}
	return nil
}

func (_u *WaChatUpdateOne) sqlSave(ctx context.Context) (_node *WaChat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wachat.Table, wachat.Columns, sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WaChat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wachat.FieldID)
		for _, f := range fields {
			if !wachat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wachat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Jid(); ok {
		_spec.SetField(wachat.FieldJid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(wachat.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(wachat.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.UnreadCount(); ok {
		_spec.SetField(wachat.FieldUnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnreadCount(); ok {
		_spec.AddField(wachat.FieldUnreadCount, field.TypeInt, value)
	}
	if _u.mutation.WaSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wachat.WaSessionTable,
			Columns: []string{wachat.WaSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WaSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wachat.WaSessionTable,
			Columns: []string{wachat.WaSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wachat.MessagesTable,
			Columns: []string{wachat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wachat.MessagesTable,
			Columns: []string{wachat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wachat.MessagesTable,
			Columns: []string{wachat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WaChat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wachat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
