// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/wachat"
	"github.com/kilip/opus/api/ent/wamessage"
	"github.com/kilip/opus/api/ent/wasession"
)

// WaChatCreate is the builder for creating a WaChat entity.
type WaChatCreate struct {
	config
	mutation *WaChatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJid sets the "jid" field.
func (_c *WaChatCreate) SetJid(v string) *WaChatCreate {
	_c.mutation.SetJid(v)
	return _c
}

// SetName sets the "name" field.
func (_c *WaChatCreate) SetName(v string) *WaChatCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *WaChatCreate) SetNillableName(v *string) *WaChatCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetUnreadCount sets the "unread_count" field.
func (_c *WaChatCreate) SetUnreadCount(v int) *WaChatCreate {
	_c.mutation.SetUnreadCount(v)
	return _c
}

// SetNillableUnreadCount sets the "unread_count" field if the given value is not nil.
func (_c *WaChatCreate) SetNillableUnreadCount(v *int) *WaChatCreate {
	if v != nil {
		_c.SetUnreadCount(*v)
	}
	return _c
}

// SetWaSessionID sets the "wa_session" edge to the WaSession entity by ID.
func (_c *WaChatCreate) SetWaSessionID(id string) *WaChatCreate {
	_c.mutation.SetWaSessionID(id)
	return _c
}

// SetWaSession sets the "wa_session" edge to the WaSession entity.
func (_c *WaChatCreate) SetWaSession(v *WaSession) *WaChatCreate {
	return _c.SetWaSessionID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the WaMessage entity by IDs.
func (_c *WaChatCreate) AddMessageIDs(ids ...int) *WaChatCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the WaMessage entity.
func (_c *WaChatCreate) AddMessages(v ...*WaMessage) *WaChatCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the WaChatMutation object of the builder.
func (_c *WaChatCreate) Mutation() *WaChatMutation {
	return _c.mutation
}

// Save creates the WaChat in the database.
func (_c *WaChatCreate) Save(ctx context.Context) (*WaChat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WaChatCreate) SaveX(ctx context.Context) *WaChat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaChatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaChatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WaChatCreate) defaults() {
	if _, ok := _c.mutation.UnreadCount(); !ok {
		v := wachat.DefaultUnreadCount
		_c.mutation.SetUnreadCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WaChatCreate) check() error {
	if _, ok := _c.mutation.Jid(); !ok {
		return &ValidationError{Name: "jid", err: errors.New(`ent: missing required field "WaChat.jid"`)}
	}
	if _, ok := _c.mutation.UnreadCount(); !ok {
		return &ValidationError{Name: "unread_count", err: errors.New(`ent: missing required field "WaChat.unread_count"`)}
	}
	if len(_c.mutation.WaSessionIDs()) == 0 {
		return &ValidationError{Name: "wa_session", err: errors.New(`ent: missing required edge "WaChat.wa_session"`)}
	}
	return nil
}

func (_c *WaChatCreate) sqlSave(ctx context.Context) (*WaChat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WaChatCreate) createSpec() (*WaChat, *sqlgraph.CreateSpec) {
	var (
		_node = &WaChat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wachat.Table, sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Jid(); ok {
		_spec.SetField(wachat.FieldJid, field.TypeString, value)
		_node.Jid = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(wachat.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.UnreadCount(); ok {
		_spec.SetField(wachat.FieldUnreadCount, field.TypeInt, value)
		_node.UnreadCount = value
	}
	if nodes := _c.mutation.WaSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wachat.WaSessionTable,
			Columns: []string{wachat.WaSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.wa_session_chats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wachat.MessagesTable,
			Columns: []string{wachat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WaChat.Create().
//		SetJid(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WaChatUpsert) {
//			SetJid(v+v).
//		}).
//		Exec(ctx)
func (_c *WaChatCreate) OnConflict(opts ...sql.ConflictOption) *WaChatUpsertOne {
	_c.conflict = opts
	return &WaChatUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WaChat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WaChatCreate) OnConflictColumns(columns ...string) *WaChatUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WaChatUpsertOne{
		create: _c,
	}
}

type (
	// WaChatUpsertOne is the builder for "upsert"-ing
	//  one WaChat node.
	WaChatUpsertOne struct {
		create *WaChatCreate
	}

	// WaChatUpsert is the "OnConflict" setter.
	WaChatUpsert struct {
		*sql.UpdateSet
	}
)

// SetJid sets the "jid" field.
func (u *WaChatUpsert) SetJid(v string) *WaChatUpsert {
	u.Set(wachat.FieldJid, v)
	return u
}

// UpdateJid sets the "jid" field to the value that was provided on create.
func (u *WaChatUpsert) UpdateJid() *WaChatUpsert {
	u.SetExcluded(wachat.FieldJid)
	return u
}

// SetName sets the "name" field.
func (u *WaChatUpsert) SetName(v string) *WaChatUpsert {
	u.Set(wachat.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WaChatUpsert) UpdateName() *WaChatUpsert {
	u.SetExcluded(wachat.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *WaChatUpsert) ClearName() *WaChatUpsert {
	u.SetNull(wachat.FieldName)
	return u
}

// SetUnreadCount sets the "unread_count" field.
func (u *WaChatUpsert) SetUnreadCount(v int) *WaChatUpsert {
	u.Set(wachat.FieldUnreadCount, v)
	return u
}

// UpdateUnreadCount sets the "unread_count" field to the value that was provided on create.
func (u *WaChatUpsert) UpdateUnreadCount() *WaChatUpsert {
	u.SetExcluded(wachat.FieldUnreadCount)
	return u
}

// AddUnreadCount adds v to the "unread_count" field.
func (u *WaChatUpsert) AddUnreadCount(v int) *WaChatUpsert {
	u.Add(wachat.FieldUnreadCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WaChat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WaChatUpsertOne) UpdateNewValues() *WaChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WaChat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WaChatUpsertOne) Ignore() *WaChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WaChatUpsertOne) DoNothing() *WaChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WaChatCreate.OnConflict
// documentation for more info.
func (u *WaChatUpsertOne) Update(set func(*WaChatUpsert)) *WaChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WaChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetJid sets the "jid" field.
func (u *WaChatUpsertOne) SetJid(v string) *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.SetJid(v)
	})
}

// UpdateJid sets the "jid" field to the value that was provided on create.
func (u *WaChatUpsertOne) UpdateJid() *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.UpdateJid()
	})
}

// SetName sets the "name" field.
func (u *WaChatUpsertOne) SetName(v string) *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WaChatUpsertOne) UpdateName() *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *WaChatUpsertOne) ClearName() *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.ClearName()
	})
}

// SetUnreadCount sets the "unread_count" field.
func (u *WaChatUpsertOne) SetUnreadCount(v int) *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.SetUnreadCount(v)
	})
}

// AddUnreadCount adds v to the "unread_count" field.
func (u *WaChatUpsertOne) AddUnreadCount(v int) *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.AddUnreadCount(v)
	})
}

// UpdateUnreadCount sets the "unread_count" field to the value that was provided on create.
func (u *WaChatUpsertOne) UpdateUnreadCount() *WaChatUpsertOne {
	return u.Update(func(s *WaChatUpsert) {
		s.UpdateUnreadCount()
	})
}

// Exec executes the query.
func (u *WaChatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WaChatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WaChatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WaChatUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WaChatUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WaChatCreateBulk is the builder for creating many WaChat entities in bulk.
type WaChatCreateBulk struct {
	config
	err      error
	builders []*WaChatCreate
	conflict []sql.ConflictOption
}

// Save creates the WaChat entities in the database.
func (_c *WaChatCreateBulk) Save(ctx context.Context) ([]*WaChat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WaChat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WaChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WaChatCreateBulk) SaveX(ctx context.Context) []*WaChat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaChatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaChatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WaChat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WaChatUpsert) {
//			SetJid(v+v).
//		}).
//		Exec(ctx)
func (_c *WaChatCreateBulk) OnConflict(opts ...sql.ConflictOption) *WaChatUpsertBulk {
	_c.conflict = opts
	return &WaChatUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WaChat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WaChatCreateBulk) OnConflictColumns(columns ...string) *WaChatUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WaChatUpsertBulk{
		create: _c,
	}
}

// WaChatUpsertBulk is the builder for "upsert"-ing
// a bulk of WaChat nodes.
type WaChatUpsertBulk struct {
	create *WaChatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WaChat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WaChatUpsertBulk) UpdateNewValues() *WaChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WaChat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WaChatUpsertBulk) Ignore() *WaChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WaChatUpsertBulk) DoNothing() *WaChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WaChatCreateBulk.OnConflict
// documentation for more info.
func (u *WaChatUpsertBulk) Update(set func(*WaChatUpsert)) *WaChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WaChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetJid sets the "jid" field.
func (u *WaChatUpsertBulk) SetJid(v string) *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.SetJid(v)
	})
}

// UpdateJid sets the "jid" field to the value that was provided on create.
func (u *WaChatUpsertBulk) UpdateJid() *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.UpdateJid()
	})
}

// SetName sets the "name" field.
func (u *WaChatUpsertBulk) SetName(v string) *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WaChatUpsertBulk) UpdateName() *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *WaChatUpsertBulk) ClearName() *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.ClearName()
	})
}

// SetUnreadCount sets the "unread_count" field.
func (u *WaChatUpsertBulk) SetUnreadCount(v int) *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.SetUnreadCount(v)
	})
}

// AddUnreadCount adds v to the "unread_count" field.
func (u *WaChatUpsertBulk) AddUnreadCount(v int) *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.AddUnreadCount(v)
	})
}

// UpdateUnreadCount sets the "unread_count" field to the value that was provided on create.
func (u *WaChatUpsertBulk) UpdateUnreadCount() *WaChatUpsertBulk {
	return u.Update(func(s *WaChatUpsert) {
		s.UpdateUnreadCount()
	})
}

// Exec executes the query.
func (u *WaChatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WaChatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WaChatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WaChatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
