// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/predicate"
	"github.com/kilip/opus/api/ent/wachat"
	"github.com/kilip/opus/api/ent/wamessage"
	"github.com/kilip/opus/api/ent/wasession"
)

// WaChatQuery is the builder for querying WaChat entities.
type WaChatQuery struct {
	config
	ctx           *QueryContext
	order         []wachat.OrderOption
	inters        []Interceptor
	predicates    []predicate.WaChat
	withWaSession *WaSessionQuery
	withMessages  *WaMessageQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WaChatQuery builder.
func (_q *WaChatQuery) Where(ps ...predicate.WaChat) *WaChatQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WaChatQuery) Limit(limit int) *WaChatQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WaChatQuery) Offset(offset int) *WaChatQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WaChatQuery) Unique(unique bool) *WaChatQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WaChatQuery) Order(o ...wachat.OrderOption) *WaChatQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWaSession chains the current query on the "wa_session" edge.
func (_q *WaChatQuery) QueryWaSession() *WaSessionQuery {
	query := (&WaSessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wachat.Table, wachat.FieldID, selector),
			sqlgraph.To(wasession.Table, wasession.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wachat.WaSessionTable, wachat.WaSessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMessages chains the current query on the "messages" edge.
func (_q *WaChatQuery) QueryMessages() *WaMessageQuery {
	query := (&WaMessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wachat.Table, wachat.FieldID, selector),
			sqlgraph.To(wamessage.Table, wamessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wachat.MessagesTable, wachat.MessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WaChat entity from the query.
// Returns a *NotFoundError when no WaChat was found.
func (_q *WaChatQuery) First(ctx context.Context) (*WaChat, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wachat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WaChatQuery) FirstX(ctx context.Context) *WaChat {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WaChat ID from the query.
// Returns a *NotFoundError when no WaChat ID was found.
func (_q *WaChatQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wachat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WaChatQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WaChat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WaChat entity is found.
// Returns a *NotFoundError when no WaChat entities are found.
func (_q *WaChatQuery) Only(ctx context.Context) (*WaChat, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wachat.Label}
	default:
		return nil, &NotSingularError{wachat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WaChatQuery) OnlyX(ctx context.Context) *WaChat {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WaChat ID in the query.
// Returns a *NotSingularError when more than one WaChat ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WaChatQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wachat.Label}
	default:
		err = &NotSingularError{wachat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WaChatQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WaChats.
func (_q *WaChatQuery) All(ctx context.Context) ([]*WaChat, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WaChat, *WaChatQuery]()
	return withInterceptors[[]*WaChat](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WaChatQuery) AllX(ctx context.Context) []*WaChat {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WaChat IDs.
func (_q *WaChatQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(wachat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WaChatQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WaChatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WaChatQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WaChatQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WaChatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WaChatQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WaChatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WaChatQuery) Clone() *WaChatQuery {
	if _q == nil {
		return nil
	}
	return &WaChatQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]wachat.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.WaChat{}, _q.predicates...),
		withWaSession: _q.withWaSession.Clone(),
		withMessages:  _q.withMessages.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWaSession tells the query-builder to eager-load the nodes that are connected to
// the "wa_session" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WaChatQuery) WithWaSession(opts ...func(*WaSessionQuery)) *WaChatQuery {
	query := (&WaSessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWaSession = query
	return _q
}

// WithMessages tells the query-builder to eager-load the nodes that are connected to
// the "messages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WaChatQuery) WithMessages(opts ...func(*WaMessageQuery)) *WaChatQuery {
	query := (&WaMessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMessages = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Jid string `json:"jid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WaChat.Query().
//		GroupBy(wachat.FieldJid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WaChatQuery) GroupBy(field string, fields ...string) *WaChatGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WaChatGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = wachat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Jid string `json:"jid,omitempty"`
//	}
//
//	client.WaChat.Query().
//		Select(wachat.FieldJid).
//		Scan(ctx, &v)
func (_q *WaChatQuery) Select(fields ...string) *WaChatSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WaChatSelect{WaChatQuery: _q}
	sbuild.label = wachat.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WaChatSelect configured with the given aggregations.
func (_q *WaChatQuery) Aggregate(fns ...AggregateFunc) *WaChatSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WaChatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !wachat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WaChatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WaChat, error) {
	var (
		nodes       = []*WaChat{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withWaSession != nil,
			_q.withMessages != nil,
		}
	)
	if _q.withWaSession != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, wachat.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WaChat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WaChat{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWaSession; query != nil {
		if err := _q.loadWaSession(ctx, query, nodes, nil,
			func(n *WaChat, e *WaSession) { n.Edges.WaSession = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMessages; query != nil {
		if err := _q.loadMessages(ctx, query, nodes,
			func(n *WaChat) { n.Edges.Messages = []*WaMessage{} },
			func(n *WaChat, e *WaMessage) { n.Edges.Messages = append(n.Edges.Messages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WaChatQuery) loadWaSession(ctx context.Context, query *WaSessionQuery, nodes []*WaChat, init func(*WaChat), assign func(*WaChat, *WaSession)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*WaChat)
	for i := range nodes {
		if nodes[i].wa_session_chats == nil {
			continue
		}
		fk := *nodes[i].wa_session_chats
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(wasession.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "wa_session_chats" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WaChatQuery) loadMessages(ctx context.Context, query *WaMessageQuery, nodes []*WaChat, init func(*WaChat), assign func(*WaChat, *WaMessage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*WaChat)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.WaMessage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wachat.MessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.wa_chat_messages
		if fk == nil {
			return fmt.Errorf(`foreign-key "wa_chat_messages" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "wa_chat_messages" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *WaChatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WaChatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wachat.Table, wachat.Columns, sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wachat.FieldID)
		for i := range fields {
			if fields[i] != wachat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WaChatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(wachat.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = wachat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WaChatGroupBy is the group-by builder for WaChat entities.
type WaChatGroupBy struct {
	selector
	build *WaChatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WaChatGroupBy) Aggregate(fns ...AggregateFunc) *WaChatGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WaChatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WaChatQuery, *WaChatGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WaChatGroupBy) sqlScan(ctx context.Context, root *WaChatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WaChatSelect is the builder for selecting fields of WaChat entities.
type WaChatSelect struct {
	*WaChatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WaChatSelect) Aggregate(fns ...AggregateFunc) *WaChatSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WaChatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WaChatQuery, *WaChatSelect](ctx, _s.WaChatQuery, _s, _s.inters, v)
}

func (_s *WaChatSelect) sqlScan(ctx context.Context, root *WaChatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
