// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/wacontact"
	"github.com/kilip/opus/api/ent/wasession"
)

// WaContactCreate is the builder for creating a WaContact entity.
type WaContactCreate struct {
	config
	mutation *WaContactMutation
	hooks    []Hook
}

// SetJid sets the "jid" field.
func (_c *WaContactCreate) SetJid(v string) *WaContactCreate {
	_c.mutation.SetJid(v)
	return _c
}

// SetName sets the "name" field.
func (_c *WaContactCreate) SetName(v string) *WaContactCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPushname sets the "pushname" field.
func (_c *WaContactCreate) SetPushname(v string) *WaContactCreate {
	_c.mutation.SetPushname(v)
	return _c
}

// SetNillablePushname sets the "pushname" field if the given value is not nil.
func (_c *WaContactCreate) SetNillablePushname(v *string) *WaContactCreate {
	if v != nil {
		_c.SetPushname(*v)
	}
	return _c
}

// SetWaSessionID sets the "wa_session" edge to the WaSession entity by ID.
func (_c *WaContactCreate) SetWaSessionID(id string) *WaContactCreate {
	_c.mutation.SetWaSessionID(id)
	return _c
}

// SetWaSession sets the "wa_session" edge to the WaSession entity.
func (_c *WaContactCreate) SetWaSession(v *WaSession) *WaContactCreate {
	return _c.SetWaSessionID(v.ID)
}

// Mutation returns the WaContactMutation object of the builder.
func (_c *WaContactCreate) Mutation() *WaContactMutation {
	return _c.mutation
}

// Save creates the WaContact in the database.
func (_c *WaContactCreate) Save(ctx context.Context) (*WaContact, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WaContactCreate) SaveX(ctx context.Context) *WaContact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaContactCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaContactCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WaContactCreate) check() error {
	if _, ok := _c.mutation.Jid(); !ok {
		return &ValidationError{Name: "jid", err: errors.New(`ent: missing required field "WaContact.jid"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "WaContact.name"`)}
	}
	if len(_c.mutation.WaSessionIDs()) == 0 {
		return &ValidationError{Name: "wa_session", err: errors.New(`ent: missing required edge "WaContact.wa_session"`)}
	}
	return nil
}

func (_c *WaContactCreate) sqlSave(ctx context.Context) (*WaContact, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WaContactCreate) createSpec() (*WaContact, *sqlgraph.CreateSpec) {
	var (
		_node = &WaContact{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wacontact.Table, sqlgraph.NewFieldSpec(wacontact.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Jid(); ok {
		_spec.SetField(wacontact.FieldJid, field.TypeString, value)
		_node.Jid = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(wacontact.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Pushname(); ok {
		_spec.SetField(wacontact.FieldPushname, field.TypeString, value)
		_node.Pushname = value
	}
	if nodes := _c.mutation.WaSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wacontact.WaSessionTable,
			Columns: []string{wacontact.WaSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.wa_session_contacts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WaContactCreateBulk is the builder for creating many WaContact entities in bulk.
type WaContactCreateBulk struct {
	config
	err      error
	builders []*WaContactCreate
}

// Save creates the WaContact entities in the database.
func (_c *WaContactCreateBulk) Save(ctx context.Context) ([]*WaContact, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WaContact, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WaContactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WaContactCreateBulk) SaveX(ctx context.Context) []*WaContact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaContactCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaContactCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
