// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kilip/opus/api/ent/predicate"
	"github.com/kilip/opus/api/ent/user"
	"github.com/kilip/opus/api/ent/wachat"
	"github.com/kilip/opus/api/ent/wacontact"
	"github.com/kilip/opus/api/ent/wamessage"
	"github.com/kilip/opus/api/ent/wasession"
)

// WaSessionUpdate is the builder for updating WaSession entities.
type WaSessionUpdate struct {
	config
	hooks    []Hook
	mutation *WaSessionMutation
}

// Where appends a list predicates to the WaSessionUpdate builder.
func (_u *WaSessionUpdate) Where(ps ...predicate.WaSession) *WaSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJid sets the "jid" field.
func (_u *WaSessionUpdate) SetJid(v string) *WaSessionUpdate {
	_u.mutation.SetJid(v)
	return _u
}

// SetNillableJid sets the "jid" field if the given value is not nil.
func (_u *WaSessionUpdate) SetNillableJid(v *string) *WaSessionUpdate {
	if v != nil {
		_u.SetJid(*v)
	}
	return _u
}

// ClearJid clears the value of the "jid" field.
func (_u *WaSessionUpdate) ClearJid() *WaSessionUpdate {
	_u.mutation.ClearJid()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WaSessionUpdate) SetStatus(v string) *WaSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WaSessionUpdate) SetNillableStatus(v *string) *WaSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *WaSessionUpdate) SetUserID(id string) *WaSessionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WaSessionUpdate) SetUser(v *User) *WaSessionUpdate {
	return _u.SetUserID(v.ID)
}

// AddContactIDs adds the "contacts" edge to the WaContact entity by IDs.
func (_u *WaSessionUpdate) AddContactIDs(ids ...int) *WaSessionUpdate {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the WaContact entity.
func (_u *WaSessionUpdate) AddContacts(v ...*WaContact) *WaSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// AddChatIDs adds the "chats" edge to the WaChat entity by IDs.
func (_u *WaSessionUpdate) AddChatIDs(ids ...int) *WaSessionUpdate {
	_u.mutation.AddChatIDs(ids...)
	return _u
}

// AddChats adds the "chats" edges to the WaChat entity.
func (_u *WaSessionUpdate) AddChats(v ...*WaChat) *WaSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the WaMessage entity by IDs.
func (_u *WaSessionUpdate) AddMessageIDs(ids ...int) *WaSessionUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the WaMessage entity.
func (_u *WaSessionUpdate) AddMessages(v ...*WaMessage) *WaSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the WaSessionMutation object of the builder.
func (_u *WaSessionUpdate) Mutation() *WaSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WaSessionUpdate) ClearUser() *WaSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearContacts clears all "contacts" edges to the WaContact entity.
func (_u *WaSessionUpdate) ClearContacts() *WaSessionUpdate {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to WaContact entities by IDs.
func (_u *WaSessionUpdate) RemoveContactIDs(ids ...int) *WaSessionUpdate {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to WaContact entities.
func (_u *WaSessionUpdate) RemoveContacts(v ...*WaContact) *WaSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// ClearChats clears all "chats" edges to the WaChat entity.
func (_u *WaSessionUpdate) ClearChats() *WaSessionUpdate {
	_u.mutation.ClearChats()
	return _u
}

// RemoveChatIDs removes the "chats" edge to WaChat entities by IDs.
func (_u *WaSessionUpdate) RemoveChatIDs(ids ...int) *WaSessionUpdate {
	_u.mutation.RemoveChatIDs(ids...)
	return _u
}

// RemoveChats removes "chats" edges to WaChat entities.
func (_u *WaSessionUpdate) RemoveChats(v ...*WaChat) *WaSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatIDs(ids...)
}

// ClearMessages clears all "messages" edges to the WaMessage entity.
func (_u *WaSessionUpdate) ClearMessages() *WaSessionUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to WaMessage entities by IDs.
func (_u *WaSessionUpdate) RemoveMessageIDs(ids ...int) *WaSessionUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to WaMessage entities.
func (_u *WaSessionUpdate) RemoveMessages(v ...*WaMessage) *WaSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WaSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WaSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WaSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WaSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WaSessionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WaSession.user"`)
	}
	return nil
}

func (_u *WaSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wasession.Table, wasession.Columns, sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Jid(); ok {
		_spec.SetField(wasession.FieldJid, field.TypeString, value)
	}
	if _u.mutation.JidCleared() {
		_spec.ClearField(wasession.FieldJid, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(wasession.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   wasession.UserTable,
			Columns: []string{wasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   wasession.UserTable,
			Columns: []string{wasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ContactsTable,
			Columns: []string{wasession.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wacontact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ContactsTable,
			Columns: []string{wasession.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wacontact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ContactsTable,
			Columns: []string{wasession.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wacontact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ChatsTable,
			Columns: []string{wasession.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatsIDs(); len(nodes) > 0 && !_u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ChatsTable,
			Columns: []string{wasession.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ChatsTable,
			Columns: []string{wasession.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.MessagesTable,
			Columns: []string{wasession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.MessagesTable,
			Columns: []string{wasession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.MessagesTable,
			Columns: []string{wasession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wasession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WaSessionUpdateOne is the builder for updating a single WaSession entity.
type WaSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WaSessionMutation
}

// SetJid sets the "jid" field.
func (_u *WaSessionUpdateOne) SetJid(v string) *WaSessionUpdateOne {
	_u.mutation.SetJid(v)
	return _u
}

// SetNillableJid sets the "jid" field if the given value is not nil.
func (_u *WaSessionUpdateOne) SetNillableJid(v *string) *WaSessionUpdateOne {
	if v != nil {
		_u.SetJid(*v)
	}
	return _u
}

// ClearJid clears the value of the "jid" field.
func (_u *WaSessionUpdateOne) ClearJid() *WaSessionUpdateOne {
	_u.mutation.ClearJid()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WaSessionUpdateOne) SetStatus(v string) *WaSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WaSessionUpdateOne) SetNillableStatus(v *string) *WaSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *WaSessionUpdateOne) SetUserID(id string) *WaSessionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WaSessionUpdateOne) SetUser(v *User) *WaSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddContactIDs adds the "contacts" edge to the WaContact entity by IDs.
func (_u *WaSessionUpdateOne) AddContactIDs(ids ...int) *WaSessionUpdateOne {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the WaContact entity.
func (_u *WaSessionUpdateOne) AddContacts(v ...*WaContact) *WaSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// AddChatIDs adds the "chats" edge to the WaChat entity by IDs.
func (_u *WaSessionUpdateOne) AddChatIDs(ids ...int) *WaSessionUpdateOne {
	_u.mutation.AddChatIDs(ids...)
	return _u
}

// AddChats adds the "chats" edges to the WaChat entity.
func (_u *WaSessionUpdateOne) AddChats(v ...*WaChat) *WaSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the WaMessage entity by IDs.
func (_u *WaSessionUpdateOne) AddMessageIDs(ids ...int) *WaSessionUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the WaMessage entity.
func (_u *WaSessionUpdateOne) AddMessages(v ...*WaMessage) *WaSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the WaSessionMutation object of the builder.
func (_u *WaSessionUpdateOne) Mutation() *WaSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WaSessionUpdateOne) ClearUser() *WaSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearContacts clears all "contacts" edges to the WaContact entity.
func (_u *WaSessionUpdateOne) ClearContacts() *WaSessionUpdateOne {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to WaContact entities by IDs.
func (_u *WaSessionUpdateOne) RemoveContactIDs(ids ...int) *WaSessionUpdateOne {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to WaContact entities.
func (_u *WaSessionUpdateOne) RemoveContacts(v ...*WaContact) *WaSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// ClearChats clears all "chats" edges to the WaChat entity.
func (_u *WaSessionUpdateOne) ClearChats() *WaSessionUpdateOne {
	_u.mutation.ClearChats()
	return _u
}

// RemoveChatIDs removes the "chats" edge to WaChat entities by IDs.
func (_u *WaSessionUpdateOne) RemoveChatIDs(ids ...int) *WaSessionUpdateOne {
	_u.mutation.RemoveChatIDs(ids...)
	return _u
}

// RemoveChats removes "chats" edges to WaChat entities.
func (_u *WaSessionUpdateOne) RemoveChats(v ...*WaChat) *WaSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatIDs(ids...)
}

// ClearMessages clears all "messages" edges to the WaMessage entity.
func (_u *WaSessionUpdateOne) ClearMessages() *WaSessionUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to WaMessage entities by IDs.
func (_u *WaSessionUpdateOne) RemoveMessageIDs(ids ...int) *WaSessionUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to WaMessage entities.
func (_u *WaSessionUpdateOne) RemoveMessages(v ...*WaMessage) *WaSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the WaSessionUpdate builder.
func (_u *WaSessionUpdateOne) Where(ps ...predicate.WaSession) *WaSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WaSessionUpdateOne) Select(field string, fields ...string) *WaSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WaSession entity.
func (_u *WaSessionUpdateOne) Save(ctx context.Context) (*WaSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WaSessionUpdateOne) SaveX(ctx context.Context) *WaSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WaSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WaSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WaSessionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WaSession.user"`)
	}
	return nil
}

func (_u *WaSessionUpdateOne) sqlSave(ctx context.Context) (_node *WaSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wasession.Table, wasession.Columns, sqlgraph.NewFieldSpec(wasession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WaSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wasession.FieldID)
		for _, f := range fields {
			if !wasession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wasession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Jid(); ok {
		_spec.SetField(wasession.FieldJid, field.TypeString, value)
	}
	if _u.mutation.JidCleared() {
		_spec.ClearField(wasession.FieldJid, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(wasession.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   wasession.UserTable,
			Columns: []string{wasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   wasession.UserTable,
			Columns: []string{wasession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ContactsTable,
			Columns: []string{wasession.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wacontact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ContactsTable,
			Columns: []string{wasession.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wacontact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ContactsTable,
			Columns: []string{wasession.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wacontact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ChatsTable,
			Columns: []string{wasession.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatsIDs(); len(nodes) > 0 && !_u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ChatsTable,
			Columns: []string{wasession.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.ChatsTable,
			Columns: []string{wasession.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wachat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.MessagesTable,
			Columns: []string{wasession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.MessagesTable,
			Columns: []string{wasession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wasession.MessagesTable,
			Columns: []string{wasession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wamessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WaSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wasession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
