// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WaChat is the predicate function for wachat builders.
type WaChat func(*sql.Selector)

// WaContact is the predicate function for wacontact builders.
type WaContact func(*sql.Selector)

// WaMessage is the predicate function for wamessage builders.
type WaMessage func(*sql.Selector)

// WaSession is the predicate function for wasession builders.
type WaSession func(*sql.Selector)
