// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kilip/opus/api/internal/repository/queue (interfaces: QueueDriver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_queue_driver.go -package=mocks github.com/kilip/opus/api/internal/repository/queue QueueDriver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/kilip/opus/api/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueDriver is a mock of QueueDriver interface.
type MockQueueDriver struct {
	ctrl     *gomock.Controller
	recorder *MockQueueDriverMockRecorder
	isgomock struct{}
}

// MockQueueDriverMockRecorder is the mock recorder for MockQueueDriver.
type MockQueueDriverMockRecorder struct {
	mock *MockQueueDriver
}

// NewMockQueueDriver creates a new mock instance.
func NewMockQueueDriver(ctrl *gomock.Controller) *MockQueueDriver {
	mock := &MockQueueDriver{ctrl: ctrl}
	mock.recorder = &MockQueueDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueDriver) EXPECT() *MockQueueDriverMockRecorder {
	return m.recorder
}

// DeleteCron mocks base method.
func (m *MockQueueDriver) DeleteCron(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCron", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCron indicates an expected call of DeleteCron.
func (mr *MockQueueDriverMockRecorder) DeleteCron(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCron", reflect.TypeOf((*MockQueueDriver)(nil).DeleteCron), ctx, id)
}

// DeleteDeadLetter mocks base method.
func (m *MockQueueDriver) DeleteDeadLetter(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeadLetter", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeadLetter indicates an expected call of DeleteDeadLetter.
func (mr *MockQueueDriverMockRecorder) DeleteDeadLetter(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeadLetter", reflect.TypeOf((*MockQueueDriver)(nil).DeleteDeadLetter), ctx, id)
}

// ListDeadLetters mocks base method.
func (m *MockQueueDriver) ListDeadLetters(ctx context.Context, limit, offset int) ([]*model.DeadLetter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeadLetters", ctx, limit, offset)
	ret0, _ := ret[0].([]*model.DeadLetter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeadLetters indicates an expected call of ListDeadLetters.
func (mr *MockQueueDriverMockRecorder) ListDeadLetters(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeadLetters", reflect.TypeOf((*MockQueueDriver)(nil).ListDeadLetters), ctx, limit, offset)
}

// ListPendingCrons mocks base method.
func (m *MockQueueDriver) ListPendingCrons(ctx context.Context) ([]*model.CronSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingCrons", ctx)
	ret0, _ := ret[0].([]*model.CronSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingCrons indicates an expected call of ListPendingCrons.
func (mr *MockQueueDriverMockRecorder) ListPendingCrons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingCrons", reflect.TypeOf((*MockQueueDriver)(nil).ListPendingCrons), ctx)
}

// MoveToDead mocks base method.
func (m *MockQueueDriver) MoveToDead(ctx context.Context, job *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToDead", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToDead indicates an expected call of MoveToDead.
func (mr *MockQueueDriverMockRecorder) MoveToDead(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToDead", reflect.TypeOf((*MockQueueDriver)(nil).MoveToDead), ctx, job)
}

// Pop mocks base method.
func (m *MockQueueDriver) Pop(ctx context.Context) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pop", ctx)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pop indicates an expected call of Pop.
func (mr *MockQueueDriverMockRecorder) Pop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pop", reflect.TypeOf((*MockQueueDriver)(nil).Pop), ctx)
}

// Push mocks base method.
func (m *MockQueueDriver) Push(ctx context.Context, job *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockQueueDriverMockRecorder) Push(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockQueueDriver)(nil).Push), ctx, job)
}

// Reschedule mocks base method.
func (m *MockQueueDriver) Reschedule(ctx context.Context, job *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reschedule", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reschedule indicates an expected call of Reschedule.
func (mr *MockQueueDriverMockRecorder) Reschedule(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reschedule", reflect.TypeOf((*MockQueueDriver)(nil).Reschedule), ctx, job)
}

// RetryDeadLetter mocks base method.
func (m *MockQueueDriver) RetryDeadLetter(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryDeadLetter", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryDeadLetter indicates an expected call of RetryDeadLetter.
func (mr *MockQueueDriverMockRecorder) RetryDeadLetter(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryDeadLetter", reflect.TypeOf((*MockQueueDriver)(nil).RetryDeadLetter), ctx, id)
}

// UpdateCronNextRun mocks base method.
func (m *MockQueueDriver) UpdateCronNextRun(ctx context.Context, id string, lastRun, nextRun time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCronNextRun", ctx, id, lastRun, nextRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCronNextRun indicates an expected call of UpdateCronNextRun.
func (mr *MockQueueDriverMockRecorder) UpdateCronNextRun(ctx, id, lastRun, nextRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCronNextRun", reflect.TypeOf((*MockQueueDriver)(nil).UpdateCronNextRun), ctx, id, lastRun, nextRun)
}

// UpdateStatus mocks base method.
func (m *MockQueueDriver) UpdateStatus(ctx context.Context, id string, status model.JobStatus, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockQueueDriverMockRecorder) UpdateStatus(ctx, id, status, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockQueueDriver)(nil).UpdateStatus), ctx, id, status, errMsg)
}

// UpsertCron mocks base method.
func (m *MockQueueDriver) UpsertCron(ctx context.Context, cron *model.CronSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCron", ctx, cron)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCron indicates an expected call of UpsertCron.
func (mr *MockQueueDriverMockRecorder) UpsertCron(ctx, cron any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCron", reflect.TypeOf((*MockQueueDriver)(nil).UpsertCron), ctx, cron)
}
