// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kilip/opus/api/internal/service (interfaces: WhatsAppService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_whatsapp_service.go -package=mocks github.com/kilip/opus/api/internal/service WhatsAppService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWhatsAppService is a mock of WhatsAppService interface.
type MockWhatsAppService struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppServiceMockRecorder
	isgomock struct{}
}

// MockWhatsAppServiceMockRecorder is the mock recorder for MockWhatsAppService.
type MockWhatsAppServiceMockRecorder struct {
	mock *MockWhatsAppService
}

// NewMockWhatsAppService creates a new mock instance.
func NewMockWhatsAppService(ctrl *gomock.Controller) *MockWhatsAppService {
	mock := &MockWhatsAppService{ctrl: ctrl}
	mock.recorder = &MockWhatsAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsAppService) EXPECT() *MockWhatsAppServiceMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockWhatsAppService) Connect(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockWhatsAppServiceMockRecorder) Connect(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockWhatsAppService)(nil).Connect), ctx, userID)
}

// Disconnect mocks base method.
func (m *MockWhatsAppService) Disconnect(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockWhatsAppServiceMockRecorder) Disconnect(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockWhatsAppService)(nil).Disconnect), ctx, userID)
}

// ForceReconnect mocks base method.
func (m *MockWhatsAppService) ForceReconnect(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceReconnect", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceReconnect indicates an expected call of ForceReconnect.
func (mr *MockWhatsAppServiceMockRecorder) ForceReconnect(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceReconnect", reflect.TypeOf((*MockWhatsAppService)(nil).ForceReconnect), ctx, userID)
}

// GetStatus mocks base method.
func (m *MockWhatsAppService) GetStatus(ctx context.Context, userID string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockWhatsAppServiceMockRecorder) GetStatus(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockWhatsAppService)(nil).GetStatus), ctx, userID)
}

// Initialize mocks base method.
func (m *MockWhatsAppService) Initialize(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockWhatsAppServiceMockRecorder) Initialize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockWhatsAppService)(nil).Initialize), ctx)
}

// SendMessage mocks base method.
func (m *MockWhatsAppService) SendMessage(ctx context.Context, userID, targetJID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, userID, targetJID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockWhatsAppServiceMockRecorder) SendMessage(ctx, userID, targetJID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockWhatsAppService)(nil).SendMessage), ctx, userID, targetJID, message)
}
