// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kilip/opus/api/internal/service (interfaces: AuthServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_auth_service.go -package=mocks github.com/kilip/opus/api/internal/service AuthServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/kilip/opus/api/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// IssueTokens mocks base method.
func (m *MockAuthServiceInterface) IssueTokens(ctx context.Context, userID string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokens", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueTokens indicates an expected call of IssueTokens.
func (mr *MockAuthServiceInterfaceMockRecorder) IssueTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokens", reflect.TypeOf((*MockAuthServiceInterface)(nil).IssueTokens), ctx, userID)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout(ctx context.Context, rawRefreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, rawRefreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout(ctx, rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout), ctx, rawRefreshToken)
}

// RefreshTokens mocks base method.
func (m *MockAuthServiceInterface) RefreshTokens(ctx context.Context, rawRefreshToken string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, rawRefreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAuthServiceInterfaceMockRecorder) RefreshTokens(ctx, rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAuthServiceInterface)(nil).RefreshTokens), ctx, rawRefreshToken)
}

// UpsertOAuthUser mocks base method.
func (m *MockAuthServiceInterface) UpsertOAuthUser(ctx context.Context, provider, providerID, email, name, avatarURL string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOAuthUser", ctx, provider, providerID, email, name, avatarURL)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertOAuthUser indicates an expected call of UpsertOAuthUser.
func (mr *MockAuthServiceInterfaceMockRecorder) UpsertOAuthUser(ctx, provider, providerID, email, name, avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOAuthUser", reflect.TypeOf((*MockAuthServiceInterface)(nil).UpsertOAuthUser), ctx, provider, providerID, email, name, avatarURL)
}

// ValidateAccessToken mocks base method.
func (m *MockAuthServiceInterface) ValidateAccessToken(tokenString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockAuthServiceInterfaceMockRecorder) ValidateAccessToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockAuthServiceInterface)(nil).ValidateAccessToken), tokenString)
}
