// Code generated by ent, DO NOT EDIT.

package deadletter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kilip/opus/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldJobID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldType, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v []byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldPayload, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldLastError, v))
}

// Retries applies equality check predicate on the "retries" field. It's identical to RetriesEQ.
func Retries(v int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldRetries, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldCreatedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldJobID, v))
}

// JobIDContains applies the Contains predicate on the "job_id" field.
func JobIDContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldJobID, v))
}

// JobIDHasPrefix applies the HasPrefix predicate on the "job_id" field.
func JobIDHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldJobID, v))
}

// JobIDHasSuffix applies the HasSuffix predicate on the "job_id" field.
func JobIDHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldJobID, v))
}

// JobIDEqualFold applies the EqualFold predicate on the "job_id" field.
func JobIDEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldJobID, v))
}

// JobIDContainsFold applies the ContainsFold predicate on the "job_id" field.
func JobIDContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldJobID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldType, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v []byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v []byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...[]byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...[]byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v []byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v []byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v []byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v []byte) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldPayload, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldLastError, v))
}

// RetriesEQ applies the EQ predicate on the "retries" field.
func RetriesEQ(v int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldRetries, v))
}

// RetriesNEQ applies the NEQ predicate on the "retries" field.
func RetriesNEQ(v int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldRetries, v))
}

// RetriesIn applies the In predicate on the "retries" field.
func RetriesIn(vs ...int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldRetries, vs...))
}

// RetriesNotIn applies the NotIn predicate on the "retries" field.
func RetriesNotIn(vs ...int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldRetries, vs...))
}

// RetriesGT applies the GT predicate on the "retries" field.
func RetriesGT(v int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldRetries, v))
}

// RetriesGTE applies the GTE predicate on the "retries" field.
func RetriesGTE(v int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldRetries, v))
}

// RetriesLT applies the LT predicate on the "retries" field.
func RetriesLT(v int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldRetries, v))
}

// RetriesLTE applies the LTE predicate on the "retries" field.
func RetriesLTE(v int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldRetries, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeadLetter) predicate.DeadLetter {
	return predicate.DeadLetter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeadLetter) predicate.DeadLetter {
	return predicate.DeadLetter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeadLetter) predicate.DeadLetter {
	return predicate.DeadLetter(sql.NotPredicates(p))
}
